#a2lix/translation-form-bundle
a2lix_translation_form:
  default_locale: en             # [1-b]
  locale_provider: default       # [1]
  locales: [en, fr, es, de]      # [1-a]
  required_locales: [fr]         # [1-c]
  templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [2]