twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - '@PhoneNumber/Form/phone_number_bootstrap_5.html.twig'
      # - '@PhoneNumber/Form/phone_number.html.twig'
      - 'bootstrap_5_layout.html.twig'
    globals:
      locales: '%app.locales%'
    paths:
      'assets/images': images
      'assets/styles': styles


when@test:
    twig:
        strict_variables: true
